// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuy2jX8mzeB_nR_okMv3nXXaJS6apQLe0',
    appId: '1:481204178559:web:7268e650bd8334c8d8b94a',
    messagingSenderId: '481204178559',
    projectId: 'trip-10ef1',
    authDomain: 'trip-10ef1.firebaseapp.com',
    storageBucket: 'trip-10ef1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxSaPBqeu5u_O9He8l90Rn0MyVNyn8Fg',
    appId: '1:481204178559:android:d801e6960d70ffb9d8b94a',
    messagingSenderId: '481204178559',
    projectId: 'trip-10ef1',
    storageBucket: 'trip-10ef1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJhIrXAY43W66vPgwvjAsYyx5y46lGzB0',
    appId: '1:481204178559:ios:a4114f09b35904b8d8b94a',
    messagingSenderId: '481204178559',
    projectId: 'trip-10ef1',
    storageBucket: 'trip-10ef1.firebasestorage.app',
    iosBundleId: 'com.example.tripIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJhIrXAY43W66vPgwvjAsYyx5y46lGzB0',
    appId: '1:481204178559:ios:a4114f09b35904b8d8b94a',
    messagingSenderId: '481204178559',
    projectId: 'trip-10ef1',
    storageBucket: 'trip-10ef1.firebasestorage.app',
    iosBundleId: 'com.example.tripIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuy2jX8mzeB_nR_okMv3nXXaJS6apQLe0',
    appId: '1:481204178559:web:849adccd170297c1d8b94a',
    messagingSenderId: '481204178559',
    projectId: 'trip-10ef1',
    authDomain: 'trip-10ef1.firebaseapp.com',
    storageBucket: 'trip-10ef1.firebasestorage.app',
  );
}
